### PR TITLE
Validate the `Contiguous` impls

### PR DESCRIPTION
**Pull request by DJMcNab**
As discussed in https://github.com/linebender/color/pull/81#discussion_r1871613918

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
We'd need it to validate that the `MAX_VALUE` + 1 (if less than the current type size's max value) is not valid. That's the case that is most likely to fail ... when someone adds a variant and forgets to update.

And at that point, it would be better if this were generic and not copy/paste for each type as I have changes in Peniko that do this for 3 more types and will later have another 3-5 enums to do ...

**Review by tomcur — APPROVED** [review]
Very cool that this is possible. To me it seems like a reasonable trade-off between code complexity and having confidence the unsafe impls remain correct. When [`std::mem::variant_count`](https://doc.rust-lang.org/std/mem/fn.variant_count.html) becomes available on stable, all necessary conditions could be tested.

**Comment by tomcur** [comment]
> We'd need it to validate that the `MAX_VALUE` + 1 (if less than the current type size's max value) is not valid.

The `compile_fail` doctests do that, it's quite neat.

**Comment by waywardmonkeys** [comment]
oh, now that I'm actually thinking and not distracted by chores, what I asked for isn't possible, I guess until that new thing is stable like @tomcur said.

**Comment by DJMcNab** [comment]
> And at that point, it would be better if this were generic and not copy/paste for each type as I have changes in Peniko that do this for 3 more types and will later have another 3-5 enums to do ...

That would require it to be a macro - a macro creating doctests should be possible, but it would be extremely ugly.

**Pull request merged**
