### PR TITLE
Derive `PartialEq` for `AlphaColor`, `OpaqueColor`, `PremulColor`

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
A possible issue here is that `DynamicColor` has a manual impl for `PartialEq` where it directly does a comparison of the bits.

**Review by raphlinus — APPROVED** [review]
Riiight, that's the reason I didn't do this before.

I think we need a `PartialEq`, so I'm approving this. What's far less clear is what semantics it should have. In particular, I don't think we should guarantee that a color component of 0.0 is equal to a color component of -0.0, ie reserve the right to make that change. Of course we're making no stability guarantees at this point.

**Comment by tomcur** [comment]
I wonder whether it makes sense to follow #75 and `impl PartialEq`, `Hash` based on the bits. There is some divergence between the types, with `DynamicColor` not being `bytemuck::Pod`, so maybe that informs the decision. An alternative is to provide the required functionality on `DynamicColor` (maybe `to_bits`) so users can themselves implement `Hash`, `Eq` on some wrapping type.

**Review by tomcur — APPROVED** [review]
(Happy for this to land as-is.)

**Comment by waywardmonkeys** [comment]
Landed this as is ... I need to do some stuff for `Default` as well so that we can use this with Parley which requires that a `Brush` impl `PartialEq` and `Default`.

**Pull request merged**
