### PR TITLE
Add `map_lightness` example

### PR DESCRIPTION
**Pull request by tomcur**

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
I liked your `swatch!` thing and wish it was here perhaps. Maybe.

**Review by DJMcNab — APPROVED** [review]
Seems useful. The same concern with the other examples that there are other versions of these methods. But not wanting to repeat the same example is also fine.

**Comment by tomcur** [comment]
We could repeat the examples, or change #56 to link to them. I'll just merge this, and we can decide in #56.

**Comment by tomcur** [comment]
> I don't think we want to block this on swatches, but I'd be happy to?

I think we haven't really made a decision yet whether it's nice enough to add. I also don't want to block this on that.

**Pull request merged**
